### ISSUE TITLE
[details/weapons]: Fix missing icons in weapons table

### ISSUE THREAD

**Issue by pinpox** [megaclan3000/megaclan3000#119]
Some Icons are missing in the table:

![image](https://user-images.githubusercontent.com/1719781/85924850-29413a80-b895-11ea-8293-e1cc3d4e425c.png)

**Comment by moritzpflueger** [comment]
this could be because I wasn't super strict with lowercase/uppercase when I handcopied all the weapon names.

e.g. I used `/Famas.jpg` instead of `famas.jpg` or `/AK47.jpg` instead of `/ak47.jpg`

I don't have this issue locally (might be transpiled by my IDE..?) 

I'll adjust the file names and have @pinpox test the result on his end

**Comment by pinpox** [comment]
fixed by #120

**Comment by pinpox** [comment]
On windows it doesn't matter, on linux it does. The server runs linux. ([more info](https://stackoverflow.com/questions/7199039/file-paths-in-windows-environment-not-case-sensitive))
